# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: news-feed-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-crawler-deployment
  namespace: news-feed-services
  labels:
    app: newsfeed-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsfeed-crawler
  template:
    metadata:
      labels:
        app: newsfeed-crawler
    spec:
      containers:
        - name: newsfeed-crawler
          image: norcodes/newsfeed-crawler:237c4e1ade47c4b40d01fa12eca785e120a09540
          # ports:
          #   - containerPort: 8082